### ISSUE TITLE
Meadow csv script

### ISSUE THREAD

**Issue by dzellner** [nulib/nul-rdc-scripts#2]
Hi Josh,

I cloned the repository and run the run.py script and got the error below.  Thanks for your help,  Dan

C:\Users\dzellner>\\library.northwestern.edu\cab\StaffDocs\dzellner\Documents\GitHub\nul-rdc-scripts\Meadow\meadow_csv_script\meadow_csv_script\run.py -i Z:\ACTIVE_AV\P0371-AtRisk-Greenglass-2022\group1 -o C:\Users\dzellner\Desktop\TEST\test.csv
Traceback (most recent call last):
  File "\\library.northwestern.edu\cab\StaffDocs\dzellner\Documents\GitHub\nul-rdc-scripts\Meadow\meadow_csv_script\meadow_csv_script\run.py", line 12, in <module>
    main()
  File "\\library.northwestern.edu\cab\StaffDocs\dzellner\Documents\GitHub\nul-rdc-scripts\Meadow\meadow_csv_script\meadow_csv_script\run.py", line 8, in main
    from meadow_csv_script import meadow_csv_mainfunc
  File "\\library.northwestern.edu\cab\StaffDocs\dzellner\Documents\GitHub\nul-rdc-scripts\Meadow\meadow_csv_script\meadow_csv_script\meadow_csv_script\meadow_csv_mainfunc.py", line 22
    inventorydf = pd.concat([pd.read_csv(inv, skiprows=0, header=0') for inv in inventories])
                                                                                             ^
SyntaxError: EOL while scanning string literal

**Comment by jyocum** [comment]
Use the script in the [mig_av](https://github.com/nulib/nul-rdc-scripts/tree/main/Meadow/mig_av) folder.

The script in the meadow_csv_script folder is only for use with image inventories where the Meadow fields just need to be separated out of the inventory. I can rename that folder and expand the description for it so that its use is clearer. It hasn't been updated in a while.

**Comment by jyocum** [comment]
I updated the name to image CSV script to denote that the script is specifically for image inventories.
