### ISSUE TITLE
mig_av error being thrown

### ISSUE THREAD

**Issue by dzellner** [nulib/nul-rdc-scripts#7]
Tried running script against Z:\ACTIVE_AV\P0094-afri-films-reel-to-reel-audio (does not contain csv file)
Here's the error that was thrown:
++ WARNING: Unable to find CSV inventory file +++
CONTINUE? (y/n)  y
Traceback (most recent call last):
  File "C:\Users\dzellner\github\nul-rdc-scripts\Meadow\mig_av\run.py", line 12, in <module>
    main()
  File "C:\Users\dzellner\github\nul-rdc-scripts\Meadow\mig_av\run.py", line 9, in main
    mig_av.mig_av_main()
  File "C:\Users\dzellner\github\nul-rdc-scripts\Meadow\mig_av\mig_av\mig_av.py", line 215, in mig_av_main
    name = item['filename']
KeyError: 'filename'

**Comment by jyocum** [comment]
This is a case of the input being set up incorrectly.
